version: '3'
services:
  server:
    image: node:lts
    container_name: chat_server
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./node_modules:/node_modules
      - ./libs:/libs
      - ./services/server:/services/server
    ports:
      - '3000:3000'
    command: yarn run ts-node-dev -r tsconfig-paths/register services/server dev