version: '3'
services:
  server:
    image: node:lts
    container_name: chat_server
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./node_modules:/node_modules
      - ./libs:/libs
      - ./services/server:/services/server
    ports:
      - '3000:3000'
      - '3001:3001'
    command: yarn run ts-node-dev -r tsconfig-paths/register services/server dev

  mongodb:
    image: mongo:4
    container_name: chat_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: K7H6cWFUgLdYO5RBfh8YWzbOCiJnMkQZ